/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ned.microservices.account.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AccountCreatedEvent extends org.apache.avro.specific.SpecificRecordBase {
  private static final long serialVersionUID = -5293409414838964291L;

  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
      "{\"type\":\"record\",\"name\":\"AccountCreatedEvent\",\"namespace\":\"com.ned.microservices.account.event\",\"fields\":[{\"name\":\"customerId\",\"type\":\"int\"},{\"name\":\"accountId\",\"type\":\"long\"}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AccountCreatedEvent> ENCODER = new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountCreatedEvent> DECODER = new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * 
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AccountCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * 
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AccountCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the
   * specified {@link SchemaStore}.
   * 
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given
   *         SchemaStore
   */
  public static BinaryMessageDecoder<AccountCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AccountCreatedEvent to a ByteBuffer.
   * 
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AccountCreatedEvent from a ByteBuffer.
   * 
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AccountCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into
   *                             an instance of this class
   */
  public static AccountCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int customerId;
  private long accountId;

  /**
   * Default constructor. Note that this does not initialize fields
   * to their default values from the schema. If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountCreatedEvent() {
  }

  /**
   * All-args constructor.
   * 
   * @param customerId The new value for customerId
   * @param accountId  The new value for accountId
   */
  public AccountCreatedEvent(java.lang.Integer customerId, java.lang.Long accountId) {
    this.customerId = customerId;
    this.accountId = accountId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  @Override
  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter. Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return customerId;
      case 1:
        return accountId;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader. Applications should not call.
  @Override
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        customerId = (java.lang.Integer) value$;
        break;
      case 1:
        accountId = (java.lang.Long) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'customerId' field.
   * 
   * @return The value of the 'customerId' field.
   */
  public int getCustomerId() {
    return customerId;
  }

  /**
   * Sets the value of the 'customerId' field.
   * 
   * @param value the value to set.
   */
  public void setCustomerId(int value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'accountId' field.
   * 
   * @return The value of the 'accountId' field.
   */
  public long getAccountId() {
    return accountId;
  }

  /**
   * Sets the value of the 'accountId' field.
   * 
   * @param value the value to set.
   */
  public void setAccountId(long value) {
    this.accountId = value;
  }

  /**
   * Creates a new AccountCreatedEvent RecordBuilder.
   * 
   * @return A new AccountCreatedEvent RecordBuilder
   */
  public static com.ned.microservices.account.event.AccountCreatedEvent.Builder newBuilder() {
    return new com.ned.microservices.account.event.AccountCreatedEvent.Builder();
  }

  /**
   * Creates a new AccountCreatedEvent RecordBuilder by copying an existing
   * Builder.
   * 
   * @param other The existing builder to copy.
   * @return A new AccountCreatedEvent RecordBuilder
   */
  public static com.ned.microservices.account.event.AccountCreatedEvent.Builder newBuilder(
      com.ned.microservices.account.event.AccountCreatedEvent.Builder other) {
    if (other == null) {
      return new com.ned.microservices.account.event.AccountCreatedEvent.Builder();
    } else {
      return new com.ned.microservices.account.event.AccountCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new AccountCreatedEvent RecordBuilder by copying an existing
   * AccountCreatedEvent instance.
   * 
   * @param other The existing instance to copy.
   * @return A new AccountCreatedEvent RecordBuilder
   */
  public static com.ned.microservices.account.event.AccountCreatedEvent.Builder newBuilder(
      com.ned.microservices.account.event.AccountCreatedEvent other) {
    if (other == null) {
      return new com.ned.microservices.account.event.AccountCreatedEvent.Builder();
    } else {
      return new com.ned.microservices.account.event.AccountCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AccountCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountCreatedEvent> {

    private int customerId;
    private long accountId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * 
     * @param other The existing Builder to copy.
     */
    private Builder(com.ned.microservices.account.event.AccountCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.customerId)) {
        this.customerId = data().deepCopy(fields()[0].schema(), other.customerId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.accountId)) {
        this.accountId = data().deepCopy(fields()[1].schema(), other.accountId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AccountCreatedEvent instance
     * 
     * @param other The existing instance to copy.
     */
    private Builder(com.ned.microservices.account.event.AccountCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.customerId)) {
        this.customerId = data().deepCopy(fields()[0].schema(), other.customerId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accountId)) {
        this.accountId = data().deepCopy(fields()[1].schema(), other.accountId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Gets the value of the 'customerId' field.
     * 
     * @return The value.
     */
    public int getCustomerId() {
      return customerId;
    }

    /**
     * Sets the value of the 'customerId' field.
     * 
     * @param value The value of 'customerId'.
     * @return This builder.
     */
    public com.ned.microservices.account.event.AccountCreatedEvent.Builder setCustomerId(int value) {
      validate(fields()[0], value);
      this.customerId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'customerId' field has been set.
     * 
     * @return True if the 'customerId' field has been set, false otherwise.
     */
    public boolean hasCustomerId() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'customerId' field.
     * 
     * @return This builder.
     */
    public com.ned.microservices.account.event.AccountCreatedEvent.Builder clearCustomerId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'accountId' field.
     * 
     * @return The value.
     */
    public long getAccountId() {
      return accountId;
    }

    /**
     * Sets the value of the 'accountId' field.
     * 
     * @param value The value of 'accountId'.
     * @return This builder.
     */
    public com.ned.microservices.account.event.AccountCreatedEvent.Builder setAccountId(long value) {
      validate(fields()[1], value);
      this.accountId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'accountId' field has been set.
     * 
     * @return True if the 'accountId' field has been set, false otherwise.
     */
    public boolean hasAccountId() {
      return fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'accountId' field.
     * 
     * @return This builder.
     */
    public com.ned.microservices.account.event.AccountCreatedEvent.Builder clearAccountId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AccountCreatedEvent build() {
      try {
        AccountCreatedEvent record = new AccountCreatedEvent();
        record.customerId = fieldSetFlags()[0] ? this.customerId : (java.lang.Integer) defaultValue(fields()[0]);
        record.accountId = fieldSetFlags()[1] ? this.accountId : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountCreatedEvent> WRITER$ = (org.apache.avro.io.DatumWriter<AccountCreatedEvent>) MODEL$
      .createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out)
      throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountCreatedEvent> READER$ = (org.apache.avro.io.DatumReader<AccountCreatedEvent>) MODEL$
      .createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in)
      throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out)
      throws java.io.IOException {
    out.writeInt(this.customerId);

    out.writeLong(this.accountId);

  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in)
      throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.customerId = in.readInt();

      this.accountId = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            this.customerId = in.readInt();
            break;

          case 1:
            this.accountId = in.readLong();
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}
